### ISSUE TITLE
Reading Intervall > 60 Sec - Error message

### ISSUE THREAD

**Issue by Csepp** [derenback/Domoticz-SMA-Inverter#21]
Dear Derenback, 

if I put the reading intervall above 60 sec. I will get an Error on the log:
"Hardware  - thread seems to have ended unexcectetly"

Have any idea? 
Greetings P.

**Comment by derenback** [comment]
Oh, I have not thought of this as an actual test case. Need to test this but I guess the plugin is sleeping a bit to long and usually you want a lot faster updates. I will test and see if I can solve this in a good way but for now I would recommend setting the interval between 5 and 30 seconds.

**Comment by derenback** [comment]
This is a known issue: https://www.domoticz.com/wiki/Developing_a_Python_plugin#Callbacks
"Warning: Setting this interval to greater than 30 seconds will cause a 'thread seems to have ended unexpectedly' message to be written to the log file every 30 seconds. The plugin will function correctly but this message can not be suppressed because it is a standard warning from Domoticz that a piece of hardware may have stopped responding.
If a plugin wants to heartbeat every 100 seconds it should be coded with the heartbeat interval set to 10, 20 or 25 seconds and only take action every 6th, 5th or 4th time the callback is invoked."

I will try to change the implementation to heartbeat every 5 seconds even if the update interval is set to a higher value.

**Comment by derenback** [comment]
A fix in version 0.9.7. Update to latest and this problem should be fixed.

**Comment by Csepp** [comment]
Dear David, 
thank you indeed. Wow great fast fix. 
Have a great time, 
Sepp
